### PR TITLE
Fix building on aarch64 (fixes #77)

### LINKED ISSUE #77: Build on Raspberry Pi runs into error
Hi!
First of all: thanks for implementing PQC-algorithms in Rust!
Compiling your crate on Windows11 and macOS works perfectly. But on an RasPi the following error occurs.
Do you have an idea how to solve the problem?
Thanks in advance,
Holger

warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S: Assembler messages:
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:138: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v0,v1,v2,v3},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:139: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v4,v5,v6,v7},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:140: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v8,v9,v10,v11},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:141: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v12,v13,v14,v15},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:142: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v16,v17,v18,v19},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:143: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v20,v21,v22,v23},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:144: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v24},[x0]'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v25,v0,v5,v10'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v26,v1,v6,v11'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v27,v2,v7,v12'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v28,v3,v8,v13'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v29,v4,v9,v14'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v25,v25,v15,v20'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v26,v26,v16,v21'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v27,v27,v17,v22'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v28,v28,v18,v23'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v29,v29,v19,v24'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v30,v29,v26'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v29,v27,v29'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v27,v25,v27'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v25,v28,v25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v28,v26,v28'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor.16b' -- `eor.16b v0,v0,v30'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v31,v1'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v1,v6,v27,20'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v6,v9,v25,44'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v9,v22,v28,3'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v22,v14,v25,25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v14,v20,v30,46'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v20,v2,v28,2'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v2,v12,v28,21'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v12,v13,v29,39'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v13,v19,v25,56'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v19,v23,v29,8'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v23,v15,v30,23'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v15,v4,v25,37'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v4,v24,v25,50'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v24,v21,v27,62'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v21,v8,v29,9'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v8,v16,v27,19'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v16,v5,v30,28'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v5,v3,v29,36'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v3,v18,v29,43'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v18,v17,v28,49'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v17,v11,v27,54'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v11,v7,v28,58'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v7,v10,v30,61'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v10,v31,v27,63'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v0,v2,v1'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v1,v3,v2'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v2,v2,v4,v3'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v3,v3,v0,v4'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v4,v4,v1,v0'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v0,v25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v1,v26'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v5,v7,v6'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v6,v8,v7'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v7,v7,v9,v8'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v8,v8,v5,v9'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v9,v9,v6,v5'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v5,v25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v6,v26'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v10,v12,v11'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v11,v13,v12'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v12,v12,v14,v13'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v13,v13,v10,v14'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v14,v14,v11,v10'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v10,v25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v11,v26'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v15,v17,v16'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v16,v18,v17'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v17,v17,v19,v18'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v18,v18,v15,v19'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v19,v19,v16,v15'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v15,v25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v16,v26'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v20,v22,v21'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v21,v23,v22'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v22,v22,v24,v23'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v23,v23,v20,v24'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v24,v24,v21,v20'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v20,v25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v21,v26'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor.16b' -- `eor.16b v0,v0,v25'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:153: Error: unknown mnemonic `st1.2d' -- `st1.2d {v0,v1,v2,v3},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:154: Error: unknown mnemonic `st1.2d' -- `st1.2d {v4,v5,v6,v7},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:155: Error: unknown mnemonic `st1.2d' -- `st1.2d {v8,v9,v10,v11},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:156: Error: unknown mnemonic `st1.2d' -- `st1.2d {v12,v13,v14,v15},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:157: Error: unknown mnemonic `st1.2d' -- `st1.2d {v16,v17,v18,v19},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:158: Error: unknown mnemonic `st1.2d' -- `st1.2d {v20,v21,v22,v23},[x0],#64'
warning: pqcrypto-internals@0.2.8: cfiles/keccak2x/feat.S:159: Error: unknown mnemonic `st1.2d' -- `st1.2d {v24},[x0]'
warning: pqcrypto-internals@0.2.8: ToolExecError: Command LC_ALL="C" "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-Wall" "-Wextra" "-march=armv8-a+sha3" "-o" "/home/pi/pqc_test/target/debug/build/pqcrypto-internals-f7ac182c5712d44d/out/9cad35ea665b40e6-feat.o" "-c" "cfiles/keccak2x/feat.S" with args cc did not execute successfully (status code exit status: 1).
error: failed to run custom build command for `pqcrypto-internals v0.2.8`

Caused by:
  process didn't exit successfully: `/home/pi/pqc_test/target/debug/build/pqcrypto-internals-1fe0f67bd74e1027/build-script-build` (exit status: 1)
  --- stdout
  cargo:includepath=/home/pi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pqcrypto-internals-0.2.8/include
  OUT_DIR = Some(/home/pi/pqc_test/target/debug/build/pqcrypto-internals-f7ac182c5712d44d/out)
  OPT_LEVEL = Some(0)
  TARGET = Some(aarch64-unknown-linux-gnu)
  HOST = Some(aarch64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CC_aarch64-unknown-linux-gnu
  CC_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_linux_gnu
  CC_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(neon)
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-linux-gnu
  CFLAGS_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_linux_gnu
  CFLAGS_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  CARGO_ENCODED_RUSTFLAGS = Some()
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0
  cargo:rerun-if-env-changed=AR_aarch64-unknown-linux-gnu
  AR_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_aarch64_unknown_linux_gnu
  AR_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64-unknown-linux-gnu
  ARFLAGS_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64_unknown_linux_gnu
  ARFLAGS_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rustc-link-lib=static=pqclean_common
  cargo:rustc-link-search=native=/home/pi/pqc_test/target/debug/build/pqcrypto-internals-f7ac182c5712d44d/out
  cargo:rustc-link-lib=pqclean_common
  OUT_DIR = Some(/home/pi/pqc_test/target/debug/build/pqcrypto-internals-f7ac182c5712d44d/out)
  OPT_LEVEL = Some(0)
  TARGET = Some(aarch64-unknown-linux-gnu)
  HOST = Some(aarch64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CC_aarch64-unknown-linux-gnu
  CC_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_linux_gnu
  CC_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(neon)
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-linux-gnu
  CFLAGS_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_linux_gnu
  CFLAGS_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  CARGO_ENCODED_RUSTFLAGS = Some()
  cargo:warning=cfiles/keccak2x/feat.S: Assembler messages:
  cargo:warning=cfiles/keccak2x/feat.S:138: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v0,v1,v2,v3},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:139: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v4,v5,v6,v7},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:140: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v8,v9,v10,v11},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:141: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v12,v13,v14,v15},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:142: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v16,v17,v18,v19},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:143: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v20,v21,v22,v23},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:144: Error: unknown mnemonic `ld1.2d' -- `ld1.2d {v24},[x0]'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v25,v0,v5,v10'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v26,v1,v6,v11'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v27,v2,v7,v12'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v28,v3,v8,v13'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v29,v4,v9,v14'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v25,v25,v15,v20'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v26,v26,v16,v21'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v27,v27,v17,v22'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v28,v28,v18,v23'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor3.16b' -- `eor3.16b v29,v29,v19,v24'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v30,v29,v26'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v29,v27,v29'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v27,v25,v27'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v25,v28,v25'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `rax1.2d' -- `rax1.2d v28,v26,v28'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor.16b' -- `eor.16b v0,v0,v30'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v31,v1'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v1,v6,v27,20'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v6,v9,v25,44'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v9,v22,v28,3'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v22,v14,v25,25'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v14,v20,v30,46'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v20,v2,v28,2'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v2,v12,v28,21'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v12,v13,v29,39'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v13,v19,v25,56'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v19,v23,v29,8'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v23,v15,v30,23'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v15,v4,v25,37'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v4,v24,v25,50'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v24,v21,v27,62'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v21,v8,v29,9'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v8,v16,v27,19'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v16,v5,v30,28'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v5,v3,v29,36'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v3,v18,v29,43'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v18,v17,v28,49'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v17,v11,v27,54'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v11,v7,v28,58'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v7,v10,v30,61'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `xar.2d' -- `xar.2d v10,v31,v27,63'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v0,v2,v1'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v1,v3,v2'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v2,v2,v4,v3'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v3,v3,v0,v4'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v4,v4,v1,v0'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v0,v25'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v1,v26'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v5,v7,v6'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v6,v8,v7'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v7,v7,v9,v8'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v8,v8,v5,v9'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v9,v9,v6,v5'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v5,v25'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v6,v26'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v10,v12,v11'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v11,v13,v12'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v12,v12,v14,v13'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v13,v13,v10,v14'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v14,v14,v11,v10'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v10,v25'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v11,v26'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v15,v17,v16'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v16,v18,v17'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v17,v17,v19,v18'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v18,v18,v15,v19'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v19,v19,v16,v15'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v15,v25'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v16,v26'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v25,v20,v22,v21'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v26,v21,v23,v22'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v22,v22,v24,v23'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v23,v23,v20,v24'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `bcax.16b' -- `bcax.16b v24,v24,v21,v20'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v20,v25'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `mov.16b' -- `mov.16b v21,v26'
  cargo:warning=cfiles/keccak2x/feat.S:147: Error: unknown mnemonic `eor.16b' -- `eor.16b v0,v0,v25'
  cargo:warning=cfiles/keccak2x/feat.S:153: Error: unknown mnemonic `st1.2d' -- `st1.2d {v0,v1,v2,v3},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:154: Error: unknown mnemonic `st1.2d' -- `st1.2d {v4,v5,v6,v7},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:155: Error: unknown mnemonic `st1.2d' -- `st1.2d {v8,v9,v10,v11},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:156: Error: unknown mnemonic `st1.2d' -- `st1.2d {v12,v13,v14,v15},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:157: Error: unknown mnemonic `st1.2d' -- `st1.2d {v16,v17,v18,v19},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:158: Error: unknown mnemonic `st1.2d' -- `st1.2d {v20,v21,v22,v23},[x0],#64'
  cargo:warning=cfiles/keccak2x/feat.S:159: Error: unknown mnemonic `st1.2d' -- `st1.2d {v24},[x0]'
  exit status: 0
  exit status: 1
  cargo:warning=ToolExecError: Command LC_ALL="C" "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-Wall" "-Wextra" "-march=armv8-a+sha3" "-o" "/home/pi/pqc_test/target/debug/build/pqcrypto-internals-f7ac182c5712d44d/out/9cad35ea665b40e6-feat.o" "-c" "cfiles/keccak2x/feat.S" with args cc did not execute successfully (status code exit status: 1).

  --- stderr

  error occurred in cc-rs: Command LC_ALL="C" "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-Wall" "-Wextra" "-march=armv8-a+sha3" "-o" "/home/pi/pqc_test/target/debug/build/pqcrypto-internals-f7ac182c5712d44d/out/9cad35ea665b40e6-feat.o" "-c" "cfiles/keccak2x/feat.S" with args cc did not execute successfully (status code exit status: 1).

### PR DESCRIPTION
**Pull request by gioelece**
armv8-a does not actually support sha3, we need at least armv8.2-a.
See https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html.
Thank you!

### CODE REVIEW

File: pqcrypto-internals/build.rs [hunk 1]
```diff
@@ -62,7 +62,7 @@ fn main() {
         println!("cargo:rustc-link-lib=keccak4x")
     } else if target_arch == "aarch64" && target_env != "msvc" {
         builder
-            .flag("-march=armv8-a+sha3")
+            .flag("-march=armv8.2-a+sha3")
```
Comment (thomwiggers) [inline pqcrypto-internals/build.rs:65]: Shouldn't the `+sha3` be sufficient to catch this though?

**Review by thomwiggers — CHANGES_REQUESTED** [review]

File: pqcrypto-internals/build.rs (hunk 1 above)
Comment (thomwiggers) [reply pqcrypto-internals/build.rs:65]: Aha, buried in the docs: 

> Use of this option with architectures prior to Armv8.2-A is not supported.

so yeah this needs to be 8.2.

**Review by thomwiggers — APPROVED** [review]

**Comment by thomwiggers** [comment]
This has been released
